# Generated by Django 3.0.8 on 2020-07-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Contact', models.IntegerField(unique=True)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
    ]
